### ISSUE TITLE
Loading several dicom files

### ISSUE THREAD

**Issue by TaskKiller98** [ivmartel/dwv-vue#149]
Firstly thank you for your work producing this.

I tried to upload two dicom files using dwv api (dwv.App.loadFiles)and have faced with load-item error with the second one. Uploading any one file works fine, but when i try to upload several, only the first one is uploaded, the rest give an error. The same problem occurred when uploading the same files to the demo version - https://ivmartel.github.io/dwv-vue/demo/stable/index.html

I attach the files that caused the error for verification. Both anonymized: [test.zip](https://github.com/ivmartel/dwv-vue/files/5845037/test.zip)

Any ideas how to fix this, or is this my fault?

Thank you in advance

**Comment by ivmartel** [comment]
Hi, the error happens because both files have different orientation. The viewer does not support loading data with different orientation since it does not know it they are related or not. There is an issue on dwv to create a 'pre' loader to filter unrelated data, see [dwv/issues/646](https://github.com/ivmartel/dwv/issues/646). In the mean time, you need to sort data manually.

**Comment by TaskKiller98** [comment]
Hi,
Sorting by orientation solve the problem.

Thank you very math for your help!

**Comment by ikhizarwork** [comment]
@yardgeo how did you solved the orientation problem ? can you please help ?
